### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by jakobrosenberg** [feathersjs/feathers-client#62] opened 2016-06-15 19:44 UTC
I have set my success URI to localhost:4000/auth/success and everything is working, except Feathers isn't logging me in.

Chrome->network is showing a "callback?code=AQbg55sm..." with two feathers-jwt response cookies. Feathers.get('token') shows undefined.

Is there a way for me to access the cookies passed by/to Feathers?

**Comment by marshallswain** [comment] 2016-06-15 21:40
If you set the cookies to not be httpOnly, then you can access them directly in the browser.  You can see how I did it in the can-connect-feathers plugin, https://github.com/feathersjs/can-connect-feathers/blob/master/src/can-connect-feathers.js#L176

There's not really a problem with storing the token in a cookie as long as you don't directly consume the token from the cookie on the server.

**Comment by jakobrosenberg** [comment] 2016-06-16 08:22
The docs say that httpOnly is set to false by default and I haven't changed it.

Chrome's network tab shows the feathers-jwt cookie, but Feather's doesn't seem to be able to access it.

**Comment by marshallswain** [comment] 2016-06-16 12:52
The cookie has a short TTL, so you have to grab it immediately and move it to localStorage. I don't remember if the auth client looks for a cookie anymore.

**Comment by daffl** [comment] 2016-06-21 01:22
Closing. Please feel free to reopen with an example to reproduce if it is still a problem.

**Closed by daffl** 2016-06-21 01:22 UTC

**Comment by jakobrosenberg** [comment] 2016-06-22 06:12
Yesterday I noticed that facebook and google login were all of a sudden working. Then hours later as sudden as it had started working, it stopped.

My Feathers server run on localhost:3030 and my Vue app on localhost:4000. localhost:3030:auth/facebook redirects to localhost:4000/auth/success.

I'm not sure how to reproduce it, cause all I'm using to authenticate is this ``Feathers.authenticate()`` which is called on page load.

**Comment by marshallswain** [comment] 2016-06-22 16:17
@jakobrosenberg I would run a script immediately that moves the token from the cookie to `localStorage.feathers-jwt`, then try `app.authenticate()`.

**Comment by jakobrosenberg** [comment] 2016-06-22 16:18
@marshallswain can you point me towards an example?

**Comment by marshallswain** [comment] 2016-06-22 16:25
Since you already have your success page working, on that page you need to run a script as the first thing, so stick something like this in the <head></head>.  Note: I like to use this package when handling cookies: https://www.npmjs.com/package/cookie-storage.  You'd need to include that script tag just before the script below.

```js
window.cookieStorage = new CookieStorage();
var jwt = cookieStorage.getItem('feathers-jwt');
window.localStorage.setItem('feathers-jwt', jwt);
```

Also note that if you've customized the cookie name or the jwt storage location then you should use the customized values.  The above will work for the defaults.

**Comment by jakobrosenberg** [comment] 2016-06-22 16:27
Thank you. I'll give that a try.

**Comment by jakobrosenberg** [comment] 2016-06-23 07:30
I still can't wrap my head around this. If I ``put console.log(document.cookie)`` in the header, there's no 'feathers-jwt' anywhere.

The network tab in Chrome shows ``callback?code=******...`` and in the cookies tab for that resource it shows ``feathers-jwt *****...`` under its response cookies.

The cookie from ``callback?code=***...`` never shows up in document.cookies and I have no idea how to fetch it.

**Comment by marshallswain** [comment] 2016-06-23 15:28
Did you customize the callback in any way?  I have no clue where that `code` is coming from.

**Comment by daffl** [comment] 2016-06-23 15:40
We can reopen this if we have an example to reproduce the issue. There is an example for OAuth 2 in https://github.com/feathersjs/feathers-demos/tree/master/examples/authentication/oauth2 it uses GitHub but Facebook should work the same way.

**Comment by jakobrosenberg** [comment] 2016-06-23 21:41
@marshallswain I didn't customize the callback at all.

Server (port: 3030)
```
{
  "host": "localhost",
  "port": 3030,
  "postgres": "postgres://***",
  "public": "../public/",
  "auth": {
    "idField": "id",
    "token": {
      "secret": "***"
    },
    "successRedirect": "http://server.local:4000/auth/success/fluff/",
    "local": {},
    "facebook": {
      "clientID": "***",
      "clientSecret": "***",
      "profileFields": ["id", "displayName", "photos", "email"],
      "permissions": {
        "scope": ["email"]
      }
    }
  }
}

```

Client (port 4000)
```
var socket = io('localhost:3030')
var Feathers = feathers()
  .configure(feathers.socketio(socket))
  .configure(feathers.hooks())
  .configure(authentication({ storage: window.localStorage }))

Feathers.authenticate()
    .then(res => {
      console.log('authenticated')
    })
    .catch(err => {
      console.error('caught error while authenticating', err)
    })
```

**Comment by marshallswain** [comment] 2016-06-23 21:46
What to you get if you take out the successRedirect?

**Comment by jakobrosenberg** [comment] 2016-06-24 05:45
@marshallswain it works fine without the successRedirect.

**Comment by jakobrosenberg** [comment] 2016-06-24 06:26
If I change successRedirect to ``localhost:3030/index.html`` and insert ``console.log(document.cookie)`` in index.html I get no jwt-token. Is this intended?

**Comment by marshallswain** [comment] 2016-06-24 12:36
How about if you set `shouldSetupSuccessRoute` to false in the config?  In the docs it says it's required if you want to use your own custom page.  Maybe that's our ticket to getting this to work.

**Comment by jakobrosenberg** [comment] 2016-06-24 12:38
I was looking through the source code earlier and shouldSetupSuccessRoute is automatically set to false if there's a success route, but I'll give it a try.

**Comment by marshallswain** [comment] 2016-06-24 12:42
That's pretty much all I have configured other than the providers:

```js
{
  "host": "localhost",
  "port": 3030,
  "mongodb": "mongodb://localhost:27017/redacted",
  "public": "../public/",
  "auth": {
    "shouldSetupSuccessRoute": false,
    "shouldSetupFailureRoute": false,
    "token": {
      "secret": "redacted"
    },
    "userEndpoint": "/v1/users",
    "local": {
      "localEndpoint": "/login"
    },
    "facebook": {
      "clientID": "redacted",
      "clientSecret": "redacted",
      "profileFields": ["id", "displayName", "email"],
      "permissions": {
        "scope": ["public_profile","email"]
      }
    },
    "google": {
      "clientID": "redacted",
      "clientSecret": "redacted",
      "permissions": {
        "scope": ["profile", "email"]
      }
    }
  }
}

```

**Comment by jakobrosenberg** [comment] 2016-06-24 12:48
Setting ``shouldSetupSuccessRoute`` to false didn't change anything, but if I additionally remove ``successRedirect``, I'm forwarded to a 404 on ``localhost:3030/auth/success#_=_ ``

**Comment by marshallswain** [comment] 2016-06-24 12:50
My email's in my profile.  Wanna send me a hangout link?

**Comment by jakobrosenberg** [comment] 2016-06-24 12:54
Sent. :)

**Comment by marshallswain** [comment] 2016-06-24 12:56
Hmm it didn't come through.

**Comment by jakobrosenberg** [comment] 2016-06-24 12:58
Try mine? Just add @gmail.com to my name.

**Comment by marshallswain** [comment] 2016-06-24 13:32
@jakobrosenberg Glad we got that worked out.  Now you can get on to the important stuff in your app.  :)

**Comment by jakobrosenberg** [comment] 2016-06-24 13:33
Thanks so much for the help @marshallswain. I don't know what I would have done without your assistance. If there's anything I can do in return let me know!

**Comment by esmevane** [comment] 2016-07-18 14:54
@marshallswain / @jakobrosenberg - Either of you mind sharing what you guys did in the hangout?  :)

**Comment by marshallswain** [comment] 2016-07-18 15:28
@esmevane Yeah.  Thanks for the reminder.  If you try to redirect to a different domain name, the cookie won't get set, so you keep the successRedirect to something on the Feathers server, like `/auth/local`, then you can create a route or page for that to grab the token from the cookie and put it wherever you need it.  I chose to use a client-side solution:

```html
<html>
    <head>
        <script>
            function readCookie(name) {
                var nameEQ = name + "=";
                var ca = document.cookie.split(';');
                for(var i=0;i < ca.length;i++) {
                    var c = ca[i];
                    while (c.charAt(0) === ' ') {
                        c = c.substring(1,c.length);
                    }
                    if (c.indexOf(nameEQ) === 0) {
                        return c.substring(nameEQ.length,c.length);
                    }
                }
                return null;
            }
            var token = readCookie('feathers-jwt');
            if(token){
                window.location.href = 'http://localhost:8080/dashboard';
            }
        </script>
    </head>
    <body>
        hi!
    </body>
</html>
```

**Comment by esmevane** [comment] 2016-07-18 18:48
Hey, thanks for that!

**Comment by mdskinner** [comment] 2016-08-05 02:39
Hey, so i've been looking everywhere extensively. And all i can find is people resorting to a client side solution. nowhere does it actually mention a _working_ serverside solution to simply access and/or interrogate the user serverside.
I've got my clientside working nicely, and I am maintaining/interrogating a user on the client no problem. 
But, how does one actually get the current logged in user object on the server?

user = xxx?
user.email = 'foo@bla.com'

Additional note if of interest? I'm finding req.feathers = { provider: 'rest', token: undefined }
The auth process is not setting anything up for serverside access it would seem.

Many thanks,
PS.. I'm loving your framework and the mindset behind it.

**Comment by marshallswain** [comment] 2016-08-05 02:57
@mdskinner the `feathers-authentication@0.8.0` plugin will make this process much more straightforward out of the box.  Right now, populating the user is done in a hook.  In the next version of the plugin, we're moving the populating of the user into rest and socket middleware, so your custom stuff will be able to access it.

**Comment by marshallswain** [comment] 2016-08-05 02:59
Check out this comment: https://github.com/feathersjs/feathers-authentication/issues/261#issuecomment-237716336

**Comment by mdskinner** [comment] 2016-08-05 10:35
Thank you for your response @marshallswain 

If I append .configure(authentication()) to the end of my main _app.js_ module with `feathers-authentication@0.7.9` i get: 
`return app.service(options.tokenEndpoint).create(user).then(resolve).catch(reject);`
`TypeError: Cannot read property 'service' of undefined`

Great to see `feathers-authentication@0.8.0` is on the way, however - it seems to 404 on _/auth/local_  ?

Upon implementing `decodeToken` i'm getting:
`const token = req.feathers.token;` is returning:
 `feathers:rest Error in REST handler: `Cannot read property 'token' of undefined` +15ms`

there is definitally stable authentication in place:
```
  engine:polling writing "�42["authenticated",{"token":"xxx","data":{"id":2,"facebookId":null,"googleId":null,"email":"xxx@gmail.com","createdAt":"2016-07-30T04:29:26.636Z","updatedAt":"2016-07-30T04:29:26.636Z"}}]" +1ms
  feathers-socket-commons:events Not sending any data for auth/token created +0ms

```
I just can't access it from the backend

i'm having to use `DEBUG=* nodemon` to get any insight into whats happening, thats probably fairly normal for extensive debugging, but it would be great to see some more errors exposed to the terminal in future releases :)  i'm sure you've got lots of ideas you're working on.

Thank you again

**Comment by mdskinner** [comment] 2016-08-05 10:38
P.S.  could there possibly be any discrepancies between having REST and socket.io both thrown into the config?  The authentication currently seems to be populated nicely in socket.io's layer 

```
app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( path.join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .configure(rest())
  .configure(socketio())
  .configure(hooks())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .use('storage', localstorage({storage: storage}))
  .configure(services)
  .configure(middleware)
  // .configure(authentication())
  ;

```

**Comment by mdskinner** [comment] 2016-08-07 06:01
Ok, so after quite a bit of effort I've figured out how to implement `feathers-authentication@0.8.0` 

First and foremost I guess, _/auth/local_ 404'ing...  you need to implement:

```
const token = authentication.TokenService;
const local = authentication.LocalService;

```and
```
  app
    .configure(token())
    .configure(local())

```
I've chosen to do that in _services/authentication_

Secondly it has a nice new structure to the config, I found the only way to get the token to populate was to set _'cookies'_ to _'enabled':true_.   Please expand on this if as I'm pretty sure you should be able to access the token serverside without allowing cookies?:
```
{
  "auth": {
    "cookies": {
      "enable":true
    },
    "local": {
      "successRedirect": "/dashboard",
      "failureRedirect": "/login"
    }
  }
}

```

This allows me to interrupt the request flow and check if there is a token present, assume they're logged in:
```
  app.use(/^\/(dashboard|apps|user).*/, function (req,res,next) {
    _console.log('--- coming from authenticated|token:', req.token)_
    _console.log('--- coming from authenticated|cookies:', req.cookies)_
    if (req.token) {
      next()
    }else{
      // res.send(401) // Unauthorised
      res.redirect('/login')
    }
  })

```

Which is a good start, but not sufficient.  
My question now is two part and I'm sure fixing one will fix the other:

I'm finding the authentication _before_ hooks aren't working. I'm only ever getting a 401 Unauthorised response regardless of the above working well.  I've tried this on a clean install and they don't work by default.

I'm guessing If i can successfully `auth.populateUser()` I'd be able to interrogate the user afterwards. 

Which leads to my last point.  How do I actually get from the request token to iterating over the current logged in users properties.

Again, much appreciated.
Many thanks

**Comment by mdskinner** [comment] 2016-08-08 03:44
I've opened this in a ticket under _feathers-authentication_, probably a better place for it. 
https://github.com/feathersjs/feathers-authentication/issues/263 

Thanks
