### ISSUE TITLE
send back to server additional fields in 'params' besides 'query'

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-client#115] opened 2016-11-17 15:42 UTC
Currently only `params.query` is sent back to server and other fields in `params` are discarded. I guess this is for avoiding conflicts when people try to send back fields like `params.token` or `params.user` which are already used for certain purposes. But it brings some inconveniences when we want to send additional information back to server (mostly used for hooks). Currently we have to put the additional information in `query` under some self-defined fields (like `query.$populate` etc.) and then on the server-side we have to use a self-defined before hook to extract the information out of the `query` object. The whole process seems awkward and unnatural. 

So it would be wonderful if we also allow another certain field (could be named as `params.options` or something) sent back to server together with `params.query`. The field name (for example, `options`) is given, so we don't need to worry about conflicts.

**Comment by marshallswain** [comment] 2016-11-17 16:19
It's a good idea to stick this in a separate key.  I'd prefer that it were `params.client` or something that more explicitly states that those params aren't secure.

**Comment by eddyystop** [comment] 2016-11-17 16:22
I like `client`. I've been using `clientParams`.

**Comment by daffl** [comment] 2016-11-17 16:36
This is already being tracked with some good suggestions in https://github.com/feathersjs/feathers/issues/304.

**Comment by daffl** [comment] 2016-11-25 18:09
I'm going to close this as a duplicate of https://github.com/feathersjs/feathers/issues/304 to keep all future discussion there. I'll definitely put this for the next release though.

**Closed by daffl** 2016-11-25 18:09 UTC
